blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://grov.dev
    about: Check out the documentation before opening an issue
  - name: Discussions
    url: https://github.com/TonyStef/Grov/discussions
    about: Ask questions and discuss ideas
